# Generated by Django 4.2 on 2024-10-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
