# Generated by Django 4.2 on 2024-10-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_games_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.genre'),
        ),
        migrations.AlterField(
            model_name='games',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.studio'),
        ),
    ]
