# Generated by Django 4.2.15 on 2024-12-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_games_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='directors', verbose_name='Картинка'),
        ),
    ]
